services:
  postgres:
    image: postgres:15-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: medusa-store
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    restart: unless-stopped

  medusa:
    build: .
    container_name: medusa_backend
    command: ./start.sh
    depends_on:
      - postgres
      - redis
    ports:
      - "9000:9000"
    environment:
      NODE_ENV: production
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/medusa-store
      REDIS_URL: redis://redis:6379
    env_file:
      - .env

volumes:
  postgres_data: